# Generated by Django 3.2.10 on 2021-12-16 15:24

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN_code', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='ISBN code')),
                ('book_title', models.CharField(max_length=512, verbose_name='book title')),
                ('book_language', models.CharField(blank=True, max_length=20, null=True, verbose_name='book language')),
                ('no_of_copies', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of copies')),
                ('publication_year', models.PositiveIntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(1800), core.models.max_value_current_year], verbose_name='publication year')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['publication_year', 'book_title'],
            },
        ),
        migrations.CreateModel(
            name='Book_Item',
            fields=[
                ('bar_code', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='bar code')),
                ('book_copy_number', models.PositiveIntegerField(verbose_name='book copy number')),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='book')),
            ],
            options={
                'verbose_name': 'book item',
                'verbose_name_plural': 'book items',
                'ordering': ['bar_code', 'book'],
            },
        ),
        migrations.CreateModel(
            name='Book_Shelf',
            fields=[
                ('Shelf_ID', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ISBN code')),
                ('Shelf_No', models.CharField(max_length=4)),
                ('Floor_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Library_Actor',
            fields=[
                ('Actor_Type', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subject_Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Library_People',
            fields=[
                ('People_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Birth_Date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Department', models.CharField(blank=True, max_length=256, null=True)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('People_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library_actor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='subject')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(verbose_name='reserve date')),
                ('reserve_status', models.BooleanField(verbose_name='reserve status')),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library_people', verbose_name='borrower')),
            ],
            options={
                'verbose_name': 'book reserve',
                'verbose_name_plural': 'book reserves',
                'ordering': ['reserve_date'],
            },
        ),
        migrations.CreateModel(
            name='Book_Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from', models.DateField(verbose_name='borrowed from')),
                ('borrowed_to', models.DateField(verbose_name='borrowed to')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='actual return date')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book_item', verbose_name='book item')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library_people', verbose_name='borrower')),
            ],
            options={
                'verbose_name': 'book loan',
                'verbose_name_plural': 'book loans',
                'ordering': ['borrowed_from'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='core.Library_People', verbose_name='authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='subject'),
        ),
        migrations.AddConstraint(
            model_name='book_reserve',
            constraint=models.UniqueConstraint(fields=('borrower', 'book'), name='unique composite Book_Reserve primary key'),
        ),
        migrations.AddConstraint(
            model_name='book_loan',
            constraint=models.UniqueConstraint(fields=('borrower', 'book_item', 'borrowed_from'), name='unique composite Book_Loan primary key'),
        ),
    ]
