# Generated by Django 4.0 on 2021-12-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_library_people_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_language',
            field=models.CharField(blank=True, choices=[('A', 'Arabic'), ('E', 'English')], max_length=20, null=True, verbose_name='book language'),
        ),
    ]
