# Generated by Django 4.0 on 2021-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_shelf',
            name='Floor_No',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='Shelf_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ISBN code'),
        ),
        migrations.AlterField(
            model_name='library_actor',
            name='Actor_Type',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='library_people',
            name='People_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject_Id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
