# Generated by Django 3.2.10 on 2021-12-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_book_shelf_floor_no_alter_book_shelf_shelf_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('People_ID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Birth_Date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Department', models.CharField(blank=True, max_length=256, null=True)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('People_ID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Birth_Date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Department', models.CharField(blank=True, max_length=256, null=True)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('People_ID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Birth_Date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Department', models.CharField(blank=True, max_length=256, null=True)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('People_ID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Birth_Date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Department', models.CharField(blank=True, max_length=256, null=True)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='library_people',
            name='People_Type',
        ),
        migrations.RemoveField(
            model_name='library_people',
            name='user',
        ),
        migrations.DeleteModel(
            name='Library_Actor',
        ),
        migrations.AddField(
            model_name='book_loan',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.librarian', verbose_name='issued by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='core.Author', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='book_loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='borrower'),
        ),
        migrations.AlterField(
            model_name='book_reserve',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='borrower'),
        ),
        migrations.DeleteModel(
            name='Library_People',
        ),
    ]
