# Generated by Django 3.2.10 on 2021-12-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211216_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loan',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.librarian', verbose_name='issued by'),
        ),
    ]
