# Generated by Django 3.2.10 on 2021-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_book_loan_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='salary',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='subscribtion_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='creation_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
