# Generated by Django 3.2.10 on 2021-12-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211216_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='book_loan',
            name='issued_by',
            field=models.ForeignKey(default='ID_MAN', on_delete=django.db.models.deletion.CASCADE, to='core.librarian', verbose_name='issued by'),
        ),
    ]
