# Generated by Django 3.2.10 on 2021-12-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211216_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='member',
            name='subscribtion_date',
        ),
    ]
