# Generated by Django 4.0 on 2021-12-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211216_2001'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book_item',
            constraint=models.UniqueConstraint(fields=('book', 'book_copy_number'), name='unique book_copy_number for each book'),
        ),
    ]
