# Generated by Django 3.2.10 on 2021-12-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_book_item_unique book_copy_number for each book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loan',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.librarian', verbose_name='issued by'),
        ),
    ]
